version: 2
jobs:
  build:
    working_directory: ~/NodeBB
    docker:
      - image: circleci/node:6.10.3
      - image: circleci/mongo:3.0.14
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm
          command: npm install
